FROM scratch

ARG ARCH=arm
ADD bin/yakapi-${ARCH} /yakapi

ENV YAKAPI_PORT=8080
ENV YAKAPI_NAME="Yak Rover"
ENV YAKAPI_PROJECT_URL="https://github.com/The-Yak-Collective/yakrover"
ENV YAKAPI_ADAPTER_MOTOR="echo"

CMD ["yakapi"]