#!/bin/bash
set -e

script/build

export YAKAPI_NAME="YakAPI (development)"
export YAKAPI_PROJECT="https://github.com/The-Yak-Collective/yakapi"
export YAKAPI_MOTOR_ADAPTER="echo"
export YAKAPI_CAM_CAPTURE_PATH="./testdata/mars.jpeg"

./bin/yakapi
