name: Go Build and Test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Test
        run: go test -v ./...
      - name: Build amd64
        run: GOOS=linux GOARCH=amd64 script/build
      - name: Build arm7
        run: GOOS=linux GOARCH=arm GOARM=7 script/build
      - name: Save Builds
        uses: actions/upload-artifact@v3
        with:
          name: yakapi-binaries
          path: bin/
          retention-days: 7
