name: Go Build and Test

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - uses: actions/checkout@v3
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...